import type { Metadata } from "next";
import Link from "next/link";
import { AdminNavigation } from "@/features/admin/AdminNavigation";
import { listActivities } from "@/lib/activities";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Actividades | Administración" };

export default async function ActivitiesPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [{ saved, error }, activities] = await Promise.all([searchParams, listActivities({ includeInactive: true })]);
  return <main className="min-h-screen px-4 py-8 sm:px-6 sm:py-12"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 pb-6"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[var(--accent)]">Gallardo Camp 2026</p><h1 className="mt-2 text-3xl font-bold">Administración</h1></div><Link href="/" className="rounded-xl bg-[var(--accent)] px-4 py-2 text-sm font-bold text-white">Ir al evento</Link></header><AdminNavigation active="activities" /><div className="grid min-w-0 gap-8 py-10">
    {saved && <p role="status" className="rounded-xl bg-emerald-50 p-4 font-bold text-emerald-700">Operación realizada correctamente.</p>}{error && <p role="alert" className="rounded-xl bg-red-50 p-4 font-bold text-red-700">No se pudo realizar la operación.</p>}
    <section className="min-w-0"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-black">Agenda y actividades</h2><p className="mt-1 text-slate-600">Configura horarios, asistencia y recompensas.</p></div><Link href="/admin/activities/new" className="rounded-xl bg-[var(--primary)] px-4 py-2.5 text-sm font-bold text-white">+ Crear</Link></div><div className="mt-5 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[1100px] text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-600"><tr><th className="p-4">Día / hora</th><th className="p-4">Actividad</th><th className="p-4">Lugar</th><th className="p-4">Asistencia</th><th className="p-4">Participación</th><th className="p-4">Podio</th><th className="p-4">Estado</th><th className="p-4 text-right">Acciones</th></tr></thead><tbody className="divide-y divide-slate-200">{activities.map((a) => <tr key={a.id}><td className="p-4"><span className="block font-bold">{a.shortDate}</span><span className="text-sm text-slate-500">{a.start}–{a.end}</span></td><td className="p-4"><span className="block max-w-xs font-bold">{a.title}</span><span className="line-clamp-2 max-w-xs text-xs text-slate-500">{a.description}</span></td><td className="p-4 text-sm">{a.location}</td><td className="p-4 text-sm">{a.required ? "Obligatoria" : "Opcional"}</td><td className="p-4 font-bold">{a.participationPoints} pts</td><td className="p-4 text-sm">{a.podiumPoints ? `${a.podiumPoints.first} / ${a.podiumPoints.second} / ${a.podiumPoints.third}` : "—"}</td><td className="p-4 text-sm">{a.active ? "Activa" : "Inactiva"}</td><td className="p-4"><div className="flex justify-end gap-2"><Link href={`/admin/activities/${a.id}`} className="rounded-lg border border-[var(--primary)] px-3 py-2 text-sm font-bold text-[var(--primary)]">Editar</Link><form action={`/admin/activities/${a.id}/delete`} method="post"><button className="rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-700">Borrar</button></form></div></td></tr>)}</tbody></table></div></section>
  </div></div></main>;
}
