import "server-only";

import { randomUUID } from "node:crypto";
import { BlobServiceClient } from "@azure/storage-blob";
import { TableClient, type TableEntity } from "@azure/data-tables";
import { rankTapas } from "./tapas-ranking";
import { getUsersByIds } from "./users";
import { STORAGE_SETTINGS } from "@/config/storage";

const ITEM = "talent"; const VOTE = "vote"; const CONFIG = "config"; const CONFIG_ROW = "contest";
export type TalentContestState = "catalog" | "voting" | "ranking";
export type Talent = { id: string; name: string; description: string; participantIds: string[]; participantNames: string[]; imageUrl: string; active: boolean };
export type TalentVote = { userId: string; displayName: string; firstId: string; secondId: string; thirdId: string; createdAt: string };
export class OwnTalentVoteError extends Error {}
type TalentEntity = TableEntity<{ name: string; description: string; participantIds: string; blobName?: string; active: boolean; createdAt: string; updatedAt?: string }>;
type VoteEntity = TableEntity<{ displayName: string; firstId: string; secondId: string; thirdId: string; createdAt: string }>;
type ConfigEntity = TableEntity<{ state: TalentContestState }>;
let ready: Promise<TableClient> | undefined;

async function table() { if (!ready) ready = (async () => { const connection = process.env.AZURE_STORAGE_CONNECTION_STRING; if (!connection) throw new Error("Falta configurar Azure Storage."); const client = TableClient.fromConnectionString(connection, STORAGE_SETTINGS.tables.talents); await client.createTable(); return client; })().catch((error) => { ready = undefined; throw error; }); return ready; }
async function container() { const connection = process.env.AZURE_STORAGE_CONNECTION_STRING; if (!connection) throw new Error("Falta configurar Azure Storage."); const value = BlobServiceClient.fromConnectionString(connection).getContainerClient(STORAGE_SETTINGS.containers.talents); await value.createIfNotExists(); return value; }
function ids(value: string) { try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed.filter((id): id is string => typeof id === "string") : []; } catch { return []; } }
async function toTalent(entity: TalentEntity): Promise<Talent> { const participantIds = ids(entity.participantIds); const users = await getUsersByIds(participantIds); const imageVersion = encodeURIComponent(entity.updatedAt ?? entity.createdAt); return { id: entity.rowKey, name: entity.name, description: entity.description, participantIds, participantNames: users.map((user) => user.displayName), imageUrl: entity.blobName ? `/api/talentos/${entity.rowKey}/image?v=${imageVersion}` : "/images/talent-placeholder.png", active: entity.active }; }
function validate(input: { name: string; description: string; participantIds: string[] }) { if (input.name.trim().length < 2 || input.name.trim().length > 100 || input.description.trim().length < 5 || input.description.trim().length > 1000 || input.participantIds.length < 1) throw new Error("Datos no válidos."); }
async function upload(blobName: string, image: File) { if (!image.type.startsWith("image/") || image.size > 8 * 1024 * 1024) throw new Error("Imagen no válida."); await (await container()).getBlockBlobClient(blobName).uploadData(await image.arrayBuffer(), { blobHTTPHeaders: { blobContentType: image.type, blobCacheControl: "public, max-age=86400" } }); }

export async function listTalents(options?: { includeInactive?: boolean }) { const entities = (await table()).listEntities<TalentEntity>({ queryOptions: { filter: `PartitionKey eq '${ITEM}'` } }); const result: Talent[] = []; for await (const entity of entities) if (options?.includeInactive || entity.active) result.push(await toTalent(entity)); return result.sort((a, b) => a.name.localeCompare(b.name, "es")); }
export async function getTalent(id: string) { try { return await toTalent(await (await table()).getEntity<TalentEntity>(ITEM, id)); } catch (error) { if (typeof error === "object" && error && "statusCode" in error && error.statusCode === 404) return null; throw error; } }
export async function createTalent(input: { name: string; description: string; participantIds: string[]; image?: File }) { validate(input); const id = randomUUID(); const blobName = input.image?.size ? `${id}.jpg` : undefined; if (blobName && input.image) await upload(blobName, input.image); const entity: TalentEntity = { partitionKey: ITEM, rowKey: id, name: input.name.trim(), description: input.description.trim(), participantIds: JSON.stringify([...new Set(input.participantIds)]), ...(blobName ? { blobName } : {}), active: true, createdAt: new Date().toISOString() }; try { await (await table()).createEntity(entity); } catch (error) { if (blobName) await (await container()).deleteBlob(blobName).catch(() => undefined); throw error; } return toTalent(entity); }
export async function updateTalent(id: string, input: { name: string; description: string; participantIds: string[]; active: boolean; image?: File }) { validate(input); const client = await table(); const current = await client.getEntity<TalentEntity>(ITEM, id); const blobName = input.image?.size ? (current.blobName ?? `${id}.jpg`) : current.blobName; if (input.image?.size && blobName) await upload(blobName, input.image); await client.updateEntity({ ...current, name: input.name.trim(), description: input.description.trim(), participantIds: JSON.stringify([...new Set(input.participantIds)]), ...(blobName ? { blobName } : {}), active: input.active, updatedAt: new Date().toISOString() }, "Merge"); }
export async function deleteTalent(id: string) { const client = await table(); const entity = await client.getEntity<TalentEntity>(ITEM, id); await client.deleteEntity(ITEM, id); if (entity.blobName) await (await container()).deleteBlob(entity.blobName).catch(() => undefined); }
export async function getTalentImage(id: string) { const entity = await (await table()).getEntity<TalentEntity>(ITEM, id); if (!entity.blobName) throw new Error("La actuación no tiene imagen."); return (await container()).getBlobClient(entity.blobName).download(); }
export async function getTalentContestState(): Promise<TalentContestState> { try { return (await (await table()).getEntity<ConfigEntity>(CONFIG, CONFIG_ROW)).state; } catch (error) { if (typeof error === "object" && error && "statusCode" in error && error.statusCode === 404) { await setTalentContestState("catalog"); return "catalog"; } throw error; } }
export async function setTalentContestState(state: TalentContestState) { await (await table()).upsertEntity<ConfigEntity>({ partitionKey: CONFIG, rowKey: CONFIG_ROW, state }, "Merge"); }
export async function submitTalentVote(input: { userId: string; displayName: string; firstId: string; secondId: string; thirdId: string }) { if (await getTalentContestState() !== "voting" || new Set([input.firstId, input.secondId, input.thirdId]).size !== 3) throw new Error("Voto no válido."); const talents = await listTalents(); const active = new Set(talents.map((item) => item.id)); if (![input.firstId, input.secondId, input.thirdId].every((id) => active.has(id))) throw new Error("Actuación no disponible."); const selectedIds = new Set([input.firstId, input.secondId, input.thirdId]); if (talents.some((talent) => selectedIds.has(talent.id) && talent.participantIds.includes(input.userId))) throw new OwnTalentVoteError("No puedes votar una actuación en la que participas."); await (await table()).createEntity<VoteEntity>({ partitionKey: VOTE, rowKey: input.userId, displayName: input.displayName, firstId: input.firstId, secondId: input.secondId, thirdId: input.thirdId, createdAt: new Date().toISOString() }); }
export async function listTalentVotes(): Promise<TalentVote[]> { const entities = (await table()).listEntities<VoteEntity>({ queryOptions: { filter: `PartitionKey eq '${VOTE}'` } }); const votes: TalentVote[] = []; for await (const entity of entities) votes.push({ userId: entity.rowKey, displayName: entity.displayName, firstId: entity.firstId, secondId: entity.secondId, thirdId: entity.thirdId, createdAt: entity.createdAt }); return votes.sort((a, b) => a.displayName.localeCompare(b.displayName, "es")); }
export async function deleteTalentVote(userId: string) { if (!userId) throw new Error("Falta el participante."); await (await table()).deleteEntity(VOTE, userId); }
export function rankTalents(talents: Talent[], votes: TalentVote[]) { return rankTapas(talents, votes); }
