/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { AdminNavigation } from "@/features/admin/AdminNavigation";
import { getContestState, listTapas, listTapaVotes } from "@/lib/tapas";

export const dynamic = "force-dynamic";

export default async function AdminTapasPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [{ saved, error }, tapas, votes, state] = await Promise.all([searchParams, listTapas({ includeInactive: true }), listTapaVotes(), getContestState()]);
  const names = new Map(tapas.map((tapa) => [tapa.id, tapa.name]));
  return <main className="min-h-screen px-4 py-7 sm:px-6 sm:py-12"><div className="mx-auto max-w-7xl"><header className="flex flex-col gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[var(--accent)]">Gallardo Camp 2026</p><h1 className="mt-2 text-3xl font-black">Administración</h1></div><Link href="/" className="rounded-xl bg-[var(--accent)] px-4 py-2.5 text-center text-sm font-bold text-white">Ir al evento</Link></header><AdminNavigation active="tapas" /><div className="grid gap-8 py-7 sm:py-10">{saved && <p className="rounded-xl bg-emerald-50 p-4 font-bold text-emerald-700">Operación realizada correctamente.</p>}{error && <p className="rounded-xl bg-red-50 p-4 font-bold text-red-700">No se pudo realizar la operación.</p>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-black">Estado del concurso</h2><p className="mt-1 text-sm text-slate-600">Controla qué ven los participantes.</p></div><form action="/admin/tapas/state" method="post" className="grid grid-cols-3 gap-2"><button name="state" value="catalog" className={`rounded-xl px-3 py-2.5 text-sm font-bold ${state === "catalog" ? "bg-[var(--primary)] text-white" : "bg-slate-100"}`}>Catálogo</button><button name="state" value="voting" className={`rounded-xl px-3 py-2.5 text-sm font-bold ${state === "voting" ? "bg-[var(--accent)] text-white" : "bg-slate-100"}`}>Votación</button><button name="state" value="ranking" className={`rounded-xl px-3 py-2.5 text-sm font-bold ${state === "ranking" ? "bg-[var(--primary-dark)] text-white" : "bg-slate-100"}`}>Ranking</button></form></div></section>
    <section><div className="flex items-end justify-between gap-3"><div><h2 className="text-2xl font-black">Tapas</h2><p className="mt-1 text-slate-600">{tapas.length} propuestas registradas.</p></div><Link href="/admin/tapas/new" className="shrink-0 rounded-xl bg-[var(--primary)] px-4 py-2.5 text-sm font-bold text-white">+ Crear tapa</Link></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{tapas.map((tapa) => <article key={tapa.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><img src={tapa.imageUrl} alt="" className="aspect-square w-full object-cover" /><div className="p-4"><div className="flex justify-between gap-3"><h3 className="font-black">{tapa.name}</h3><span className={`text-xs font-bold ${tapa.active ? "text-emerald-700" : "text-slate-400"}`}>{tapa.active ? "Activa" : "Inactiva"}</span></div><p className="mt-1 text-sm text-slate-500">{tapa.participantNames.join(", ")}</p><div className="mt-4 flex gap-2"><Link href={`/admin/tapas/${tapa.id}`} className="flex-1 rounded-lg border border-[var(--primary)] px-3 py-2 text-center text-sm font-bold text-[var(--primary)]">Editar</Link><form action={`/admin/tapas/${tapa.id}/delete`} method="post"><button className="rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-700">Borrar</button></form></div></div></article>)}</div></section>
    <section><h2 className="text-2xl font-black">Votos emitidos</h2><p className="mt-1 text-slate-600">{votes.length} participantes han votado.</p>{votes.length > 0 && <div className="mt-5 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[680px] text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-600"><tr><th className="p-4">Participante</th><th className="p-4">5 puntos</th><th className="p-4">3 puntos</th><th className="p-4">1 punto</th></tr></thead><tbody className="divide-y divide-slate-200">{votes.map((vote) => <tr key={vote.userId}><td className="p-4 font-bold">{vote.displayName}</td><td className="p-4">{names.get(vote.firstId)}</td><td className="p-4">{names.get(vote.secondId)}</td><td className="p-4">{names.get(vote.thirdId)}</td></tr>)}</tbody></table></div>}</section>
  </div></div></main>;
}
