import type { Metadata } from "next";
import Link from "next/link";
import { AdminNavigation } from "@/features/admin/AdminNavigation";
import { DailyGameForm } from "@/features/admin/DailyGameForm";
import { listAllDailyGameAttempts, listConfiguredDailyGames } from "@/lib/daily-games";
import { listUsers } from "@/lib/users";
import type { DailyGames } from "@/config/daily-games";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Minijuegos | Administración" };

const emptyGames: DailyGames = { date: "", trivia: { prompt: "", options: ["", ""], correctOption: 0 }, word: { prompt: "", answer: "" }, poll: { prompt: "", options: ["", ""] } };
const labels = { trivia: "Trivia", word: "Palabra", poll: "Encuesta" } as const;

export default async function AdminGamesPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [{ saved, error }, games, attempts, users] = await Promise.all([searchParams, listConfiguredDailyGames(), listAllDailyGameAttempts(), listUsers()]);
  const userMap = new Map(users.map((user) => [user.id, user]));
  return <main className="min-h-screen px-4 py-7 sm:px-6 sm:py-12"><div className="mx-auto max-w-7xl">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 pb-6"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[var(--accent)]">Gallardo Camp 2026</p><h1 className="mt-2 text-3xl font-bold">Administración</h1></div><Link href="/juegos" className="rounded-xl bg-[var(--accent)] px-4 py-2 text-sm font-bold text-white">Ver minijuegos</Link></header>
    <AdminNavigation active="games" />
    <div className="grid gap-10 py-8">
      {saved && <p role="status" className="rounded-2xl bg-emerald-50 p-4 font-bold text-emerald-700">Operación realizada correctamente.</p>}{error && <p role="alert" className="rounded-2xl bg-red-50 p-4 font-bold text-red-700">No se pudo realizar la operación.</p>}
      <section><div><h2 className="text-2xl font-black">Retos por fecha</h2><p className="mt-2 max-w-3xl text-slate-600">Los retos del fichero aparecen por defecto. Al guardar un día se almacena en Azure y podrás seguir editándolo desde aquí.</p></div><details className="mt-5 rounded-2xl border-2 border-dashed border-[var(--primary-border)] bg-[var(--primary-subtle)]"><summary className="cursor-pointer list-none p-5 font-black text-[var(--primary-dark)]">+ Configurar una nueva fecha</summary><DailyGameForm games={emptyGames} isNew /></details><div className="mt-5 grid gap-4 lg:grid-cols-2">{games.map((day) => <details key={day.date} className="min-w-0 rounded-2xl border border-slate-200 bg-white shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 p-5"><span><strong className="block text-lg">{new Intl.DateTimeFormat("es-ES", { dateStyle: "full", timeZone: "Europe/Madrid" }).format(new Date(`${day.date}T12:00:00Z`))}</strong><span className="mt-1 block truncate text-sm text-slate-500">{day.trivia.prompt}</span></span><span className="shrink-0 text-sm font-bold text-[var(--primary)]">Editar</span></summary><div className="border-t border-slate-100"><DailyGameForm games={day} /><form action={`/admin/games/${day.date}/delete`} method="post" className="px-4 pb-5 sm:px-6"><button className="w-full rounded-xl border border-red-200 px-4 py-2.5 text-sm font-bold text-red-700">Eliminar configuración de Azure</button><p className="mt-2 text-center text-xs text-slate-500">Si esta fecha existe en el fichero, volverá a usarse su versión por defecto.</p></form></div></details>)}</div></section>
      <section><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-black">Respuestas de usuarios</h2><p className="mt-2 text-slate-600">Al borrar un acierto también se retira su punto y el usuario podrá volver a responder.</p></div><span className="rounded-full bg-[var(--primary-subtle)] px-3 py-1 text-sm font-bold text-[var(--primary-dark)]">{attempts.length} respuestas</span></div>{attempts.length === 0 ? <p className="mt-5 rounded-2xl border-2 border-dashed border-slate-200 p-8 text-center text-slate-500">Todavía no hay respuestas.</p> : <div className="mt-5 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[780px] text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-600"><tr><th className="p-4">Fecha</th><th className="p-4">Usuario</th><th className="p-4">Juego</th><th className="p-4">Respuesta</th><th className="p-4">Resultado</th><th className="p-4 text-right">Acción</th></tr></thead><tbody className="divide-y divide-slate-200">{attempts.map((attempt) => { const user = userMap.get(attempt.userId); return <tr key={`${attempt.userId}-${attempt.date}-${attempt.kind}`}><td className="p-4 text-sm font-bold">{attempt.date}</td><td className="p-4"><strong className="block">{user?.displayName ?? "Usuario eliminado"}</strong>{user && <span className="text-xs text-slate-500">@{user.username}</span>}</td><td className="p-4 text-sm">{labels[attempt.kind]}</td><td className="max-w-xs truncate p-4 text-sm">{attempt.answer}</td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${attempt.correct ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{attempt.kind === "poll" ? "+1 · Participación" : attempt.correct ? "+1 · Correcta" : "Incorrecta"}</span></td><td className="p-4 text-right"><form action={`/admin/games/attempts/${attempt.userId}/${attempt.date}/${attempt.kind}/delete`} method="post"><button className="rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-700">Eliminar respuesta</button></form></td></tr>; })}</tbody></table></div>}</section>
    </div>
  </div></main>;
}
