import type { DailyGames } from "@/config/daily-games";

const input = "w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-[var(--accent)] focus:ring-2 focus:ring-[var(--accent-soft)]";

export function DailyGameForm({ games, isNew = false }: { games: DailyGames; isNew?: boolean }) {
  return <form action="/admin/games/save" method="post" className="grid gap-5 p-4 sm:p-6">
    {!isNew && <input type="hidden" name="originalDate" value={games.date} />}
    <label className="grid gap-1 text-sm font-bold">Fecha<input name="date" type="date" required defaultValue={games.date} className={input} /></label>
    <fieldset className="grid gap-3 rounded-2xl border border-slate-200 p-4"><legend className="px-2 font-black text-[var(--primary-dark)]">Trivia diaria</legend><label className="grid gap-1 text-xs font-bold">Pregunta<input name="triviaPrompt" required minLength={5} defaultValue={games.trivia.prompt} className={input} /></label><label className="grid gap-1 text-xs font-bold">Opciones <span className="font-normal text-slate-500">Una por línea</span><textarea name="triviaOptions" required rows={4} defaultValue={games.trivia.options.join("\n")} className={`${input} resize-none`} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold">Número de respuesta correcta<input name="triviaCorrect" type="number" min={1} max={games.trivia.options.length || 10} required defaultValue={games.trivia.correctOption + 1} className={input} /></label><label className="grid gap-1 text-xs font-bold">Explicación opcional<input name="triviaExplanation" defaultValue={games.trivia.explanation} className={input} /></label></div></fieldset>
    <fieldset className="grid gap-3 rounded-2xl border border-slate-200 p-4"><legend className="px-2 font-black text-[var(--primary-dark)]">Palabra diaria</legend><label className="grid gap-1 text-xs font-bold">Enunciado<input name="wordPrompt" required minLength={5} defaultValue={games.word.prompt} className={input} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold">Respuesta<input name="wordAnswer" required minLength={2} defaultValue={games.word.answer} className={input} /></label><label className="grid gap-1 text-xs font-bold">Pista opcional<input name="wordHint" defaultValue={games.word.hint} className={input} /></label></div><label className="grid gap-1 text-xs font-bold">Explicación opcional<input name="wordExplanation" defaultValue={games.word.explanation} className={input} /></label></fieldset>
    <fieldset className="grid gap-3 rounded-2xl border border-slate-200 p-4"><legend className="px-2 font-black text-[var(--primary-dark)]">Encuesta diaria</legend><label className="grid gap-1 text-xs font-bold">Pregunta<input name="pollPrompt" required minLength={5} defaultValue={games.poll.prompt} className={input} /></label><label className="grid gap-1 text-xs font-bold">Opciones <span className="font-normal text-slate-500">Una por línea; no hay respuesta correcta</span><textarea name="pollOptions" required rows={4} defaultValue={games.poll.options.join("\n")} className={`${input} resize-none`} /></label></fieldset>
    <button className="min-h-12 rounded-xl bg-[var(--primary)] px-5 font-black text-white">{isNew ? "Crear retos del día" : "Guardar cambios"}</button>
  </form>;
}
