import type { ReactNode } from "react";
import type { Tapa } from "@/lib/tapas";
import type { User } from "@/lib/users";
import { TapaImageInput } from "./TapaImageInput";

export function TapaForm({ action, users, tapa, children }: { action: string; users: User[]; tapa?: Tapa; children?: ReactNode }) {
  const input = "rounded-xl border border-slate-300 px-4 py-3 font-normal outline-none focus:border-[var(--accent)]";
  return <form action={action} method="post" encType="multipart/form-data" className="grid gap-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-2 sm:p-8"><label className="grid gap-2 text-sm font-bold sm:col-span-2">Nombre<input name="name" required minLength={2} maxLength={100} defaultValue={tapa?.name} className={input} /></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Descripción<textarea name="description" required minLength={5} maxLength={1000} rows={4} defaultValue={tapa?.description} className={input} /></label><fieldset className="sm:col-span-2"><legend className="text-sm font-bold">Participantes responsables</legend><div className="mt-3 grid gap-2 rounded-2xl border border-slate-200 p-3 sm:grid-cols-2">{users.map((user) => <label key={user.id} className="flex min-h-11 items-center gap-3 rounded-xl px-3 hover:bg-slate-50"><input type="checkbox" name="participantIds" value={user.id} defaultChecked={tapa?.participantIds.includes(user.id)} className="h-5 w-5 accent-[var(--primary)]" /><span>{user.displayName} <span className="text-xs text-slate-500">@{user.username}</span></span></label>)}</div></fieldset><TapaImageInput required={!tapa} currentImage={tapa?.imageUrl} />{tapa && <label className="grid gap-2 text-sm font-bold">Estado<select name="active" defaultValue={String(tapa.active)} className={input}><option value="true">Activa</option><option value="false">Inactiva</option></select></label>}<div className="flex justify-end gap-3 border-t border-slate-200 pt-5 sm:col-span-2">{children}<button className="rounded-xl bg-[var(--primary)] px-5 py-3 font-bold text-white">Guardar tapa</button></div></form>;
}
