import type { Metadata } from "next";
import Link from "next/link";
import { AdminNavigation } from "@/features/admin/AdminNavigation";
import { VoucherScanner } from "@/features/admin/VoucherScanner";
import { listActivities } from "@/lib/activities";
import { listUsers } from "@/lib/users";
import { listVouchers } from "@/lib/vouchers";

export const metadata: Metadata = { title: "Validación | Administración" };

export const dynamic = "force-dynamic";

export default async function ValidationPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [{ saved, error }, users, vouchers, activities] = await Promise.all([searchParams, listUsers(), listVouchers({ includeInactive: true }), listActivities({ includeInactive: true })]);
  const input = "w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-[var(--accent)]";
  return <main className="min-h-screen px-4 py-8 sm:px-6 sm:py-12"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 pb-6"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-[var(--accent)]">Gallardo Camp 2026</p><h1 className="mt-2 text-3xl font-bold">Administración</h1></div><Link href="/" className="rounded-xl bg-[var(--accent)] px-4 py-2 text-sm font-bold text-white">Ir al evento</Link></header><AdminNavigation active="validation" /><section className="grid gap-8 py-10"><div><h2 className="text-2xl font-black">Validar puntos</h2><p className="mt-2 text-slate-600">Escanea códigos o asigna recompensas manualmente.</p></div>{saved && <p role="status" className="rounded-xl bg-emerald-50 p-4 font-bold text-emerald-700">Puntos aplicados correctamente.</p>}{error && <p role="alert" className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{error === "duplicate" ? "Este participante ya recibió los puntos de participación de esa actividad." : "No se pudieron aplicar los puntos seleccionados."}</p>}<VoucherScanner />
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-xl font-black">Asignar vale manualmente</h3><form action="/admin/vouchers/manual" method="post" className="mt-4 grid gap-4 md:grid-cols-[1fr_1fr_auto] md:items-end"><label className="grid gap-2 text-sm font-bold">Participante<select name="userId" required className={input}><option value="">Seleccionar…</option>{users.map((u) => <option key={u.id} value={u.id}>{u.displayName}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Vale<select name="voucherId" required className={input}><option value="">Seleccionar…</option>{vouchers.filter((v) => v.active).map((v) => <option key={v.id} value={v.id}>{v.title} (+{v.points})</option>)}</select></label><button className="rounded-xl bg-[var(--accent)] px-5 py-2.5 text-sm font-bold text-white">Aplicar</button></form></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-xl font-black">Asignar actividad manualmente</h3><form action="/admin/activities/award" method="post" className="mt-4 grid gap-4 lg:grid-cols-[1fr_1fr_1fr_auto] lg:items-end"><label className="grid gap-2 text-sm font-bold">Participante<select name="userId" required className={input}><option value="">Seleccionar…</option>{users.map((u) => <option key={u.id} value={u.id}>{u.displayName}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Actividad<select name="activityId" required className={input}><option value="">Seleccionar…</option>{activities.filter((a) => a.active).map((a) => <option key={a.id} value={a.id}>{a.title}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Recompensa<select name="reward" className={input}><option value="participation">Participación</option><option value="first">Primer puesto</option><option value="second">Segundo puesto</option><option value="third">Tercer puesto</option></select></label><button className="rounded-xl bg-[var(--accent)] px-5 py-2.5 text-sm font-bold text-white">Aplicar</button></form></section>
  </section></div></main>;
}
